version: "3.8"

services:
  db_dev:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-mydb}
    volumes:
      - ./postgres-dev-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
